"""Update

Revision ID: 6625c8ecd3b5
Revises: 6a87e545ae0e
Create Date: 2024-10-27 14:48:43.769386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6625c8ecd3b5'
down_revision: Union[str, None] = '6a87e545ae0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=False)
    op.alter_column('tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_tokens_token', table_name='tokens')
    op.create_unique_constraint(None, 'tokens', ['token'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'tokens', type_='unique')
    op.create_index('ix_tokens_token', 'tokens', ['token'], unique=True)
    op.alter_column('tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tokens', 'token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
