apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres
          resources:
            limits:
              cpu: 0
              memory: 0
            requests:
              cpu: 0
              memory: 0
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-configmap
            - secretRef:
                name: postgresql-secret
