# Use the official Python image as the base image
FROM python:3.10.14

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port (use the port you specified in your .env file)
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]
