version: "3"
services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - dverse-network
    restart: always
    volumes:
      - ./nats-server/nats-server.conf:/etc/nats-server.conf # Ensure the config is correctly mounted
    command: -c /etc/nats-server.conf
