# Use the official Redis image as the base
FROM redis:latest

# Copy custom configuration file (if any)
COPY redis.conf /usr/local/etc/redis/redis.conf

# Set default command to use the custom config
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
